### ISSUE TITLE
jok init doesn't work on windows

### ISSUE THREAD

**Issue by playerx** [jokio/jok-cli#1]
space problem between firstName and lastName

```
PS C:\test\jok-test> npx jok init testapp --graphql
npm ERR! code ENOLOCAL
npm ERR! Could not install from "LastName\AppData\Roaming\npm-cache\_npx\7976" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\FirstName LastName\AppData\Roaming\npm-cache\_logs\2018-11-19T17_38_28_617Z-debug.log
Install for jok@latest failed with code 1
```
```
PS C:\test\jok-test> npx jok init testapp --graphql
Error: EPERM: operation not permitted, mkdir 'C:\Users\FirstName'
TypeError: Cannot read property 'get' of undefined
    at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
    at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:78:20
    at cb (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:228:22)
    at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:266:24
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:83:7
    at Array.forEach (<anonymous>)
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:82:13
    at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
    at afterExtras (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:173:20)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\mkdirp\index.js:47:53
C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205
  if (npm.config.get('json')) {
                 ^

TypeError: Cannot read property 'get' of undefined
    at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:391:26)
Install for jok@latest failed with code 7
```

**Comment by playerx** [comment]
problem is related to `npx`. you can try installing `jok` globally and it will work
